# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 481)
        self.send_lineEdit = QtWidgets.QLineEdit(Form)
        self.send_lineEdit.setGeometry(QtCore.QRect(400, 70, 113, 161))
        self.send_lineEdit.setObjectName("send_lineEdit")
        self.rcv_textEdit = QtWidgets.QTextEdit(Form)
        self.rcv_textEdit.setGeometry(QtCore.QRect(590, 70, 104, 161))
        self.rcv_textEdit.setObjectName("rcv_textEdit")
        self.open_connect_Button = QtWidgets.QPushButton(Form)
        self.open_connect_Button.setGeometry(QtCore.QRect(40, 260, 75, 23))
        self.open_connect_Button.setObjectName("open_connect_Button")
        self.close_connect_pushButton_2 = QtWidgets.QPushButton(Form)
        self.close_connect_pushButton_2.setGeometry(QtCore.QRect(190, 260, 75, 23))
        self.close_connect_pushButton_2.setObjectName("close_connect_pushButton_2")
        self.logo_label = QtWidgets.QLabel(Form)
        self.logo_label.setGeometry(QtCore.QRect(350, 10, 54, 12))
        self.logo_label.setObjectName("logo_label")
        self.ip_lineEdit = QtWidgets.QLineEdit(Form)
        self.ip_lineEdit.setGeometry(QtCore.QRect(130, 80, 141, 31))
        self.ip_lineEdit.setObjectName("ip_lineEdit")
        self.port_lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.port_lineEdit_2.setGeometry(QtCore.QRect(130, 170, 141, 31))
        self.port_lineEdit_2.setObjectName("port_lineEdit_2")
        self.ip_label = QtWidgets.QLabel(Form)
        self.ip_label.setGeometry(QtCore.QRect(50, 90, 54, 12))
        self.ip_label.setObjectName("ip_label")
        self.port_label_2 = QtWidgets.QLabel(Form)
        self.port_label_2.setGeometry(QtCore.QRect(50, 180, 54, 12))
        self.port_label_2.setObjectName("port_label_2")
        self.send_data_pushButton = QtWidgets.QPushButton(Form)
        self.send_data_pushButton.setGeometry(QtCore.QRect(420, 280, 75, 23))
        self.send_data_pushButton.setObjectName("send_data_pushButton")
        self.rcv_pushButton_2 = QtWidgets.QPushButton(Form)
        self.rcv_pushButton_2.setGeometry(QtCore.QRect(600, 280, 75, 23))
        self.rcv_pushButton_2.setObjectName("rcv_pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.open_connect_Button.setText(_translate("Form", "建立连接"))
        self.close_connect_pushButton_2.setText(_translate("Form", "关闭连接"))
        self.logo_label.setText(_translate("Form", "客户端"))
        self.ip_label.setText(_translate("Form", "服务器ip:"))
        self.port_label_2.setText(_translate("Form", "端口号："))
        self.send_data_pushButton.setText(_translate("Form", "发送数据"))
        self.rcv_pushButton_2.setText(_translate("Form", "接收数据"))
